// nos testes, inclua como:
// const series = require( '../js/series' )

// no console, apenas copie a variável series abaixo:
const series = [
  {
    titulo: "Stranger Things",
    anoEstreia: 2016,
    diretor: ["Matt Duffer", "Ross Duffer"],
    genero: ["Suspense", "Ficcao Cientifica", "Drama"],
    elenco: [
      "Winona Ryder",
      "David Harbour",
      "Finn Wolfhard",
      "Millie Bobby Brown",
      "Gaten Matarazzo",
      "Caleb McLaughlin",
      "Natalia Dyer",
      "Charlie Heaton",
      "Cara Buono",
      "Matthew Modine",
      "Noah Schnapp",
    ],
    temporadas: 2,
    numeroEpisodios: 17,
    distribuidora: "Netflix",
  },
  {
    titulo: "Game Of Thrones",
    anoEstreia: 2011,
    diretor: [
      "David Benioff",
      "D. B. Weiss",
      "Carolyn Strauss",
      "Frank Doelger",
      "Bernadette Caulfield",
      "George R. R. Martin",
    ],
    genero: ["Fantasia", "Drama"],
    elenco: [
      "Peter Dinklage",
      "Nikolaj Coster-Waldau",
      "Lena Headey",
      "Emilia Clarke",
      "Kit Harington",
      "Aidan Gillen",
      "Iain Glen ",
      "Sophie Turner",
      "Maisie Williams",
      "Alfie Allen",
      "Isaac Hempstead Wright",
    ],
    temporadas: 7,
    numeroEpisodios: 67,
    distribuidora: "HBO",
  },
  {
    titulo: "The Walking Dead",
    anoEstreia: 2010,
    diretor: ["Jolly Dale", "Caleb Womble", "Paul Gadd", "Heather Bellson"],
    genero: ["Terror", "Suspense", "Apocalipse Zumbi"],
    elenco: [
      "Andrew Lincoln",
      "Jon Bernthal",
      "Sarah Wayne Callies",
      "Laurie Holden",
      "Jeffrey DeMunn",
      "Steven Yeun",
      "Chandler Riggs ",
      "Norman Reedus",
      "Lauren Cohan",
      "Danai Gurira",
      "Michael Rooker ",
      "David Morrissey",
    ],
    temporadas: 9,
    numeroEpisodios: 122,
    distribuidora: "AMC",
  },
  {
    titulo: "Band of Brothers",
    anoEstreia: 20001,
    diretor: [
      "Steven Spielberg",
      "Tom Hanks",
      "Preston Smith",
      "Erik Jendresen",
      "Stephen E. Ambrose",
    ],
    genero: ["Guerra"],
    elenco: [
      "Damian Lewis",
      "Donnie Wahlberg",
      "Ron Livingston",
      "Matthew Settle",
      "Neal McDonough",
    ],
    temporadas: 1,
    numeroEpisodios: 10,
    distribuidora: "HBO",
  },
  {
    titulo: "JS-Pop do G7",
    anoEstreia: 2017,
    diretor: ["Tomás", "Arthur", "Gustavo", "Pablo", "Álvaro"],
    genero: ["Terror", "Caos", "JavaScript"],
    elenco: [
      "Aline Cruz",
      "Aline Escobar",
      "Eduardo Vital",
      "Francielle Rodrigues",
      "Guilherme Karkotli",
      "Jhonata Ávila",
      "Marcos Oliveira",
      "Rafael Audibert",
    ],
    temporadas: 1,
    numeroEpisodios: 40,
    distribuidora: "TAG Livros",
  },
  {
    titulo: "10 Days Why",
    anoEstreia: 2010,
    diretor: ["Brendan Eich"],
    genero: ["Caos", "JavaScript"],
    elenco: ["Brendan Eich", "Bernardo Bosak"],
    temporadas: 10,
    numeroEpisodios: 10,
    distribuidora: "JS",
  },
  {
    titulo: "Mr. Robot",
    anoEstreia: 2018,
    diretor: ["Sam Esmail"],
    genero: ["Drama", "Techno Thriller", "Psychological Thriller"],
    elenco: [
      "Rami Malek",
      "Carly Chaikin",
      "Portia Doubleday",
      "Martin Wallström",
      "Christian Slater",
    ],
    temporadas: 3,
    numeroEpisodios: 32,
    distribuidora: "USA Network",
  },
  {
    titulo: "Narcos",
    anoEstreia: 2015,
    diretor: [
      "Paul Eckstein",
      "Mariano Carranco",
      "Tim King",
      "Lorenzo O Brien",
    ],
    genero: ["Documentario", "Crime", "Drama"],
    elenco: [
      "Wagner Moura",
      "Boyd Holbrook",
      "Pedro Pascal",
      "Joann Christie",
      "Mauricie Compte",
      "André Mattos",
      "Roberto Urbina",
      "Diego Cataño",
      "Jorge A. Jiménez",
      "Paulina Gaitán",
      "Paulina Garcia",
    ],
    temporadas: 3,
    numeroEpisodios: 30,
    distribuidora: null,
  },
  {
    titulo: "Westworld",
    anoEstreia: 2016,
    diretor: ["Athena Wickham"],
    genero: [
      "Ficcao Cientifica",
      "Drama",
      "Thriller",
      "Acao",
      "Aventura",
      "Faroeste",
    ],
    elenco: [
      "Anthony C. Meyer",
      "Thandie H. Newton",
      "Jeffrey I. Wright",
      "James K. Marsden",
      "Ben I. Barnes",
      "Ingrid B. Bolso Berdal",
      "Clifton A. Collins Jr.",
      "Luke L. Hemsworth",
      "Paul A. Rupert",
    ],
    temporadas: 2,
    numeroEpisodios: 20,
    distribuidora: "HBO",
  },
  {
    titulo: "Breaking Bad",
    anoEstreia: 2008,
    diretor: [
      "Vince Gilligan",
      "Michelle MacLaren",
      "Adam Bernstein",
      "Colin Bucksey",
      "Michael Slovis",
      "Peter Gould",
    ],
    genero: ["Acao", "Suspense", "Drama", "Crime", "Humor Negro"],
    elenco: [
      "Bryan Cranston",
      "Anna Gunn",
      "Aaron Paul",
      "Dean Norris",
      "Betsy Brandt",
      "RJ Mitte",
    ],
    temporadas: 5,
    numeroEpisodios: 62,
    distribuidora: "AMC",
  },
];

module.exports = series;
